#Site variables
title: atomikaya creates fiction.
logo: assets/logo.png
description: > # this means to ignore newlines until "baseurl:"
  English and french writer. I come here to improve on my writing as well as my regularity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atomikaya.github.io"
permalink: /stories/:categories/

paginate: 8
paginate_path: /:num/

follow:
#  patreon:
- label: Wattpad
  url: http://wattpad.com/user/atomikaya
#  webtoon:
- label: My atom feed
  url: /feed.xml

# Build settings
markdown: kramdown
# theme: minima
safe: true
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
