#Site variables
title: atomikaya creates fiction.
logo: assets/logo.png
description: >
  English and french author.Regular updates, hopefully fun stories!
  Stay tuned ;)
baseurl: ""
url: "http://atomikaya.github.io"
permalink: /stories/:categories/

paginate: 8
paginate_path: /:num/

follow:
#  patreon:
- label: Wattpad
  url: http://wattpad.com/user/atomikaya
#  webtoon:
- label: My atom feed
  url: /feed.xml

license:
  title: "Attribution NonCommercial ShareAlike"
  url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

# Build settings
markdown: kramdown
# theme: minima
safe: true
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
